### ISSUE TITLE
Błąd podczas wywołania skryptu

### ISSUE THREAD

**Issue by km4lin** [zoondo/allegro-api#1]
Witam,
podczas wywołania przykładowego skryptu otrzymuję błąd:
`Fatal error: Class 'SoapClient' not found in D:\xampp\htdocs\allegro\vendor\zoondo\allegro-api\source\AllegroApi.php on line 136`
Prośba o pomoc co tutaj może być nie tak.
Pozdrawiam

**Comment by mstraczkowski** [comment]
https://stackoverflow.com/questions/11391442/fatal-error-class-soapclient-not-found
