### ISSUE TITLE
Problem z doGetSiteJournalDeals

### ISSUE THREAD

**Issue by km4lin** [zoondo/allegro-api#2]
Witam,
próbuję uzyskać poprzez doGetSiteJournalDeals transakcje z danego dnia, oto mój kod:
`<?php // Used namespace
require __DIR__ . '/vendor/autoload.php';
use Zoondo\AllegroApi\AllegroApi;

// Creating new instance of AllegroApi
$api = new AllegroApi('mojkluczapi');

// We are going to login
$api->login(array(
    'userLogin'    => 'mojlogin',
    'userPassword' => 'mojehaslo',
    'countryCode'  => $api->getCountry(),
    'webapiKey'    => $api->getApiKey(),
    'localVersion' => $api->getVersionKey(),
));
// For now, we have an access to $api->getSession()

$response = $api->doGetSiteJournalDeals(array(
    'sessionId' => $api->getSession(),
	'journalStart' => 1519290000,
));
print_r($response);
?>`
Niestety nie ważne co wpiszę w wartości journalStart to ciągle mam ten sam wynik. Proszę o informację jak mogę w poprawny sposób przekazać datę rozpoczęcia.
Z góry dziękuję za jakąkolwiek podpowiedź.

**Comment by mstraczkowski** [comment]
https://allegro.pl/webapi/documentation.php/show/id,742
