### ISSUE TITLE
Jak dodać własne parametry do SoapClient?

### ISSUE THREAD

**Issue by juhacz** [zoondo/allegro-api#4]
Fajnie jakby była możliwość dodania swoich parametrów do soapa.
W tym momencie jest tylko 
'features' => SOAP_SINGLE_ELEMENT_ARRAYS

Ja np. potrzebuję:
 'features' => SOAP_SINGLE_ELEMENT_ARRAYS,
                'keep_alive' => true,
                'connection_timeout' => 5000,
                'cache_wsdl' => WSDL_CACHE_NONE,
                'compression'   => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | SOAP_COMPRESSION_DEFLATE

Dzięki!

**Comment by mstraczkowski** [comment]
Cześć,

Taka możliwość istnieje od zawsze za pomocą metody _setSoapClient()_
Umożliwia ona podłączenie Twojej własnej instancji SoapClient, zamiast korzystania z domyślnej.

**Przykład:**
```php
// Used namespaces
use Zoondo\AllegroApi\AllegroApi;
use SoapClient;

// Creating new instance of AllegroApi
$api = new AllegroApi('your_api_key');

// Setting new instance of SoapClient (configured by yourself)
$api->setSoapClient(new SoapClient($api->getWsdlUrl(), array(
    'features'           => SOAP_SINGLE_ELEMENT_ARRAYS,
    'keep_alive'         => true,
    'connection_timeout' => 5000,
    'cache_wsdl'         => WSDL_CACHE_NONE,
    'compression'        => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | SOAP_COMPRESSION_DEFLATE
)));

// ..... Done, you can use API
```

**Comment by juhacz** [comment]
Dzięki za wyjaśnienie.
