### ISSUE TITLE
Uncaught Error: Class 'Zoondo\AllegroApi\AllegroWebApi' not found

### ISSUE THREAD

**Issue by tsubocz** [zoondo/allegro-api#5]
Cześć,
Mam problem z podstawowym uruchomieniem skryptu - jedynie wrzuciłem:
`require_once '../../api/allegro/AllegroApi.php';
use Zoondo\AllegroApi\AllegroRestApi;
   var_dump(
    AllegroRestApi::getAuthLink($clientId, $redirectUri)
);`

i dostaje:
`Uncaught Error: Class 'Zoondo\AllegroApi\AllegroWebApi' not found in /app/panel/api/allegro/AllegroApi.php:16 Stack trace: #0 /app/panel/portal/allegro/resumption-cron.php(13): require_once() #1 {main} thrown in /app/panel/api/allegro/AllegroApi.php on line 16`
Linia 16 to własne `use Zoondo\AllegroApi\AllegroRestApi; `

Dodawałem również require_once dla wszystkich plików AllegroApi.php, AllegroRestApi.php oraz AllegroWebApi.php, ale nic się nie zmienia.

**Comment by mstraczkowski** [comment]
Na podstawie Twojego opisu chyba nie mogę za wiele pomóc, najlepiej skorzystać z composera w celu instalacji biblioteki w Twoim projekcie.

W teorii jeżeli masz zaincludowane wszystkie 3 klasy w odpowiedniej kolejności: _AllegroWebApi, AllegroRestApi, AllegroApi_ to taki problem nie powinien występować.
